#!/bin/bash -e
# set things up
mount="$(dirname "$(readlink -f "$0")")"
cd "$mount"
source loadconfig

# regenerate boot.cfg
cat > boot.cfg <<EOF
# vim: ft=grub
set root_uuid="${root_uuid}"
set root_pool="${root_pool}"
EOF

# write the config in the pool

zfs list "${root_pool}/grub" >/dev/null 2>&1 || zfs create "${root_pool}/grub"
zfs list -Ho name,eu.nathan7:boot -r "${root_pool}" | awk -F '\t' 'tolower($2) == "true" {print $1}' | cut -d/ -f2- | while read dataset; do
  cat <<EOF
menuentry "$dataset" {
  set root_fs=\${root_pool}/\${chosen}
  set root_path=/\${chosen}/@
  set boot_path=\${root_path}/boot
  source \${boot_path}/grub.cfg
}
EOF
done > "/${root_pool}/grub/grub.cfg"

# set ourselves up in a temporary dir and start building our GRUB image
dir="$(mktemp -d)"
cd "$dir"
mkdir -p boot/grub

cat "$mount/boot.cfg" - >> boot/grub/grub.cfg <<EOF
# vim: ft=grub
set timeout=0

if keystatus --shift; then
  set timeout=-1
fi

set gfxmode=auto
set gfxpayload=keep
set menu_color_normal=cyan/blue
set menu_color_highlight=blue/cyan

cryptomount -a

if keystatus --shift; then
  set timeout=-1
fi

search --no-floppy --label --set \${root_pool}
source /grub/@/grub.cfg
EOF

if command -v grub-mkstandalone > /dev/null; then
  grub_mkstandalone=grub-mkstandalone
elif command -v grub2-mkstandalone > /dev/null; then
  grub_mkstandalone=grub2-mkstandalone
else
  echo "can't find grub-mkstandalone" >&2
  exit 255
fi

${grub_mkstandalone} -O x86_64-efi --modules='gfxterm gfxmenu efi_gop efi_uga font part_gpt part_msdos luks zfs' --locales='en@quot' --themes='' -o "$mount/grubx64.efi" boot/grub/grub.cfg

rm -rf "$dir"

